### ISSUE TITLE
Error in encoder_subprocess.stdin.write(frame)

### ISSUE THREAD

**Issue by animeojisan** [JepEtau/py_temporalfix#1]
`python py_temporalfix.py --input test.mkv --output output_video.mkv`

When I run the above, I get the following error. Do you know of any solution to this problem?

```
Traceback (most recent call last):
  File "G:\temporalfix\py_temporalfix.py", line 209, in <module>
    main()
  File "G:\temporalfix\py_temporalfix.py", line 178, in main
    encoder_subprocess.stdin.write(frame)
OSError: [Errno 22] Invalid argument
```
[log-anioji.txt](https://github.com/user-attachments/files/17220307/log-anioji.txt)

**Comment by JepEtau** [comment]
for the record:
I made some corrections and modifications.
Main branch, commit [9b5c80b](https://github.com/JepEtau/py_temporalfix/commit/9b5c80b0af9710f668fe6d8ed1c09be98073d934)
